// Generated by ContextEntityGenerator
"use strict";
var EnvironmentProfile = (function () {
    function EnvironmentProfile() {
    }
    ;
    EnvironmentProfile.prototype.setAmbientLight = function (v) {
        this.ambientLight = v;
    };
    ;
    EnvironmentProfile.prototype.getAmbientLight = function () {
        return this.ambientLight;
    };
    EnvironmentProfile.prototype.setMovement = function (v) {
        this.movement = v;
    };
    ;
    EnvironmentProfile.prototype.getMovement = function () {
        return this.movement;
    };
    EnvironmentProfile.prototype.setLocation = function (v) {
        this.location = v;
    };
    ;
    EnvironmentProfile.prototype.getLocation = function () {
        return this.location;
    };
    return EnvironmentProfile;
}());
exports.EnvironmentProfile = EnvironmentProfile;
//# sourceMappingURL=environment.profile.js.map