// Generated by ContextEntityGenerator

// contains properties for environment context

import { Level } from '../types/Level';

export class EnvironmentProfile {
	
	private ambientLight: Level;
	private movement: Level;
	private location: string;
    
    constructor(){};
    
	public setAmbientLight(v: Level){
	    this.ambientLight = v;
	};
	
	public getAmbientLight(): Level{
	    return this.ambientLight;
	}
	public setMovement(v: Level){
	    this.movement = v;
	};
	
	public getMovement(): Level{
	    return this.movement;
	}
	public setLocation(v: string){
	    this.location = v;
	};
	
	public getLocation(): string{
	    return this.location;
	}
}

