// Generated by ContextProfileGenerator
"use strict";
// Is the central profile class that connects the different user-defined context-entities
var user_profile_1 = require('./user.profile');
var environment_profile_1 = require('./environment.profile');
var platform_profile_1 = require('./platform.profile');
var Profile = (function () {
    function Profile() {
        // initialize context profiles			    	
        this.user = new user_profile_1.UserProfile();
        this.environment = new environment_profile_1.EnvironmentProfile();
        this.platform = new platform_profile_1.PlatformProfile();
    }
    // get User profile
    Profile.prototype.getUser = function () {
        return this.user;
    };
    // get Environment profile
    Profile.prototype.getEnvironment = function () {
        return this.environment;
    };
    // get Platform profile
    Profile.prototype.getPlatform = function () {
        return this.platform;
    };
    return Profile;
}());
exports.Profile = Profile;
//# sourceMappingURL=profile.js.map