// Generated by ContextProviderGenerator

// Contains Objects that push new data to the Context Controller

// Code for API/Library access has to be inserted in the file:"geocoding.service.ts" 
// in the folder: static/app/context/providers/
		
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { BehaviorSubject } from 'rxjs/Rx';


// PROTECTED REGION ID general ENABLED START
declare var google: any;

// PROTECTED REGION END

@Injectable()
export class GeocodingService {
	
	private location: string;
	private _locationSubject: BehaviorSubject<string> = new BehaviorSubject("init");
	public locationSubject: Observable<string> = this._locationSubject.asObservable();
	
	// PROTECTED REGION ID geocoding ENABLED START

    private geocoder = new google.maps.Geocoder;
    private latlng = new google.maps.LatLng({lat: 51, lng:8});

	// PROTECTED REGION END
	
	constructor(){
		// PROTECTED REGION ID constructor ENABLED START


		// PROTECTED REGION END
	}
	
	getLocation(){
		
		// PROTECTED REGION ID location ENABLED START


	if (navigator.geolocation) {
		navigator.geolocation.getCurrentPosition((position: any) => {
			var la = "" + position.coords.latitude;
			var lo = "" + position.coords.longitude;
			this.latlng = new google.maps.LatLng({lat: parseFloat(la), lng: parseFloat(lo)});
		});
	} else {
		console.log('Geolocation not supported');
	}
	this.geocoder.geocode({ 'location': this.latlng }, (results: any, status:any) => {
        if (status === google.maps.GeocoderStatus.OK) {
            if (results[1]) {
                this.location = "" + results[1].formatted_address;
            } else {
                console.log('No location results found');
            }
        } else {
            console.log('Geocoder failed due to: ' + status);
        }
    });
		// PROTECTED REGION END
		
		this._locationSubject.next(this.location);
	}
}
