// Generated by ContextProviderGenerator
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
// Contains Objects that push new data to the Context Controller
// Code for API/Library access has to be inserted in the file:"geocoding.service.ts" 
// in the folder: static/app/context/providers/
var core_1 = require('@angular/core');
var Rx_1 = require('rxjs/Rx');
// PROTECTED REGION END
var GeocodingService = (function () {
    // PROTECTED REGION END
    function GeocodingService() {
        // PROTECTED REGION ID constructor ENABLED START
        this._locationSubject = new Rx_1.BehaviorSubject("init");
        this.locationSubject = this._locationSubject.asObservable();
        // PROTECTED REGION ID geocoding ENABLED START
        this.geocoder = new google.maps.Geocoder;
        this.latlng = new google.maps.LatLng({ lat: 51, lng: 8 });
        // PROTECTED REGION END
    }
    GeocodingService.prototype.getLocation = function () {
        // PROTECTED REGION ID location ENABLED START
        var _this = this;
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(function (position) {
                var la = "" + position.coords.latitude;
                var lo = "" + position.coords.longitude;
                _this.latlng = new google.maps.LatLng({ lat: parseFloat(la), lng: parseFloat(lo) });
            });
        }
        else {
            console.log('Geolocation not supported');
        }
        this.geocoder.geocode({ 'location': this.latlng }, function (results, status) {
            if (status === google.maps.GeocoderStatus.OK) {
                if (results[1]) {
                    _this.location = "" + results[1].formatted_address;
                }
                else {
                    console.log('No location results found');
                }
            }
            else {
                console.log('Geocoder failed due to: ' + status);
            }
        });
        // PROTECTED REGION END
        this._locationSubject.next(this.location);
    };
    GeocodingService = __decorate([
        core_1.Injectable(), 
        __metadata('design:paramtypes', [])
    ], GeocodingService);
    return GeocodingService;
}());
exports.GeocodingService = GeocodingService;
//# sourceMappingURL=geocoding.service.js.map