// Generated by ContextProviderGenerator

// Contains Objects that push new data to the Context Controller

// Code for API/Library access has to be inserted in the file:"weather.service.ts" 
// in the folder: static/app/context/providers/
		
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { BehaviorSubject } from 'rxjs/Rx';


// PROTECTED REGION ID general ENABLED START
// PROTECTED REGION END

@Injectable()
export class WeatherService {
	
	
	// PROTECTED REGION ID weather ENABLED START
	// PROTECTED REGION END
	
	constructor(){
		// PROTECTED REGION ID constructor ENABLED START
		// PROTECTED REGION END
	}
	
}
