// Generated by ContextProviderGenerator
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var __metadata = (this && this.__metadata) || function (k, v) {
    if (typeof Reflect === "object" && typeof Reflect.metadata === "function") return Reflect.metadata(k, v);
};
// Contains Objects that push new data to the Context Controller
// Code for API/Library access has to be inserted in the file:"weather.service.ts" 
// in the folder: static/app/context/providers/
var core_1 = require('@angular/core');
// PROTECTED REGION ID general ENABLED START
// PROTECTED REGION END
var WeatherService = (function () {
    // PROTECTED REGION ID weather ENABLED START
    // PROTECTED REGION END
    function WeatherService() {
        // PROTECTED REGION ID constructor ENABLED START
        // PROTECTED REGION END
    }
    WeatherService = __decorate([
        core_1.Injectable(), 
        __metadata('design:paramtypes', [])
    ], WeatherService);
    return WeatherService;
}());
exports.WeatherService = WeatherService;
//# sourceMappingURL=weather.service.js.map